insert into allowed_domains (domain, description) values ('satgurutravel.com','Satguru Travel corporate users'),('satguruai.com','Satguru AI administrators'),('satguruuniverse.com','Approved group domain') on conflict do nothing;
insert into departments (department_name) values ('Retail/CRM'),('Sales/Management'),('Operations'),('Travel / Holidays'),('Sales / Lead Management'),('Process/SOP'),('Cargo'),('Visa'),('Mobility'),('Contracting'),('Management'),('All Departments'),('Platform') on conflict do nothing;
insert into portal_categories (category_name, description, display_order) values ('CRM','Customer relationship management',1),('Sales','Sales intelligence and lead tools',2),('Operations','Operations workflows',3),('Knowledge','SOP and process knowledge',4),('Cargo','Cargo applications',5),('Visa','Visa applications',6),('Mobility','Mobility applications',7),('DMC','Destination management contracting',8),('Savings / Management','Savings and management tools',9),('Platform','Central platform tools',10) on conflict do nothing;
insert into portals (portal_name, portal_slug, portal_url, short_description, full_description, category_id, department_id, business_owner, technical_owner, support_email, status, visibility) values
('Retail CRM','retail-crm','https://retail-crm.satguruai.com','Customer and retail CRM related workflows.','Customer and retail CRM related workflows.',(select id from portal_categories where category_name='CRM'),(select id from departments where department_name='Retail/CRM'),'Retail/CRM Owner','Satguru AI Platform','support+retail-crm@satguruai.com','live','logged_in'),
('Satguru Sales Intelligence','sales-intelligence','https://sales-intelligence.satguruai.com','Sales intelligence, client insights, and business development analysis.','Sales intelligence, client insights, and business development analysis.',(select id from portal_categories where category_name='Sales'),(select id from departments where department_name='Sales/Management'),'Sales/Management Owner','Satguru AI Platform','support+sales-intelligence@satguruai.com','pending_dns','logged_in'),
('COPS','cops','https://cops.satguruai.com','Operational coordination and process tracking portal.','Operational coordination and process tracking portal.',(select id from portal_categories where category_name='Operations'),(select id from departments where department_name='Operations'),'Operations Owner','Satguru AI Platform','support+cops@satguruai.com','pending_dns','logged_in'),
('Holiday Itinerary','holiday-itinerary','https://holiday-itinerary.satguruai.com','Holiday itinerary creation and management.','Holiday itinerary creation and management.',(select id from portal_categories where category_name='Operations'),(select id from departments where department_name='Travel / Holidays'),'Travel / Holidays Owner','Satguru AI Platform','support+holiday-itinerary@satguruai.com','pending_dns','logged_in'),
('STG Operations','stg-ops','https://stg-ops.satguruai.com','Operational workflows and branch operations support.','Operational workflows and branch operations support.',(select id from portal_categories where category_name='Operations'),(select id from departments where department_name='Operations'),'Operations Owner','Satguru AI Platform','support+stg-ops@satguruai.com','pending_dns','logged_in'),
('STG Sales / Lead Finder','stg-sales','https://stg-sales.satguruai.com','Lead finder and sales management application.','Lead finder and sales management application.',(select id from portal_categories where category_name='Sales'),(select id from departments where department_name='Sales / Lead Management'),'Sales / Lead Management Owner','Satguru AI Platform','support+stg-sales@satguruai.com','pending_dns','logged_in'),
('Process Repository','process-repository','https://process-repository.satguruai.com','Central repository for process documents and SOPs.','Central repository for process documents and SOPs.',(select id from portal_categories where category_name='Knowledge'),(select id from departments where department_name='Process/SOP'),'Process/SOP Owner','Satguru AI Platform','support+process-repository@satguruai.com','pending_dns','logged_in'),
('Satguru Cargo','satcargo-connect','https://satcargo-connect.satguruai.com','Cargo-related workflows and connection portal.','Cargo-related workflows and connection portal.',(select id from portal_categories where category_name='Cargo'),(select id from departments where department_name='Cargo'),'Cargo Owner','Satguru AI Platform','support+satcargo-connect@satguruai.com','pending_dns','logged_in'),
('VisaDone','visadone','https://visadone.satguruai.com','Visa-related internal workflow support.','Visa-related internal workflow support.',(select id from portal_categories where category_name='Visa'),(select id from departments where department_name='Visa'),'Visa Owner','Satguru AI Platform','support+visadone@satguruai.com','pending_dns','logged_in'),
('CIA Mobility','cia-mobility','https://cia-mobility.satguruai.com','CIA mobility related portal.','CIA mobility related portal.',(select id from portal_categories where category_name='Mobility'),(select id from departments where department_name='Mobility'),'Mobility Owner','Satguru AI Platform','support+cia-mobility@satguruai.com','pending_dns','logged_in'),
('DMC Contracting','dmc-contracting','https://dmc-contracting.satguruai.com','DMC contracting workflow support.','DMC contracting workflow support.',(select id from portal_categories where category_name='DMC'),(select id from departments where department_name='Contracting'),'Contracting Owner','Satguru AI Platform','support+dmc-contracting@satguruai.com','pending_dns','logged_in'),
('Maxsave','maxsave','https://maxsave.satguruai.com','Maxsave related application.','Maxsave related application.',(select id from portal_categories where category_name='Savings / Management'),(select id from departments where department_name='Management'),'Management Owner','Satguru AI Platform','support+maxsave@satguruai.com','pending_dns','logged_in'),
('Satguru AI Central Portal','satguru-ai-central-portal','https://app.satguruai.com','Main home page and application hub.','Main home page and application hub.',(select id from portal_categories where category_name='Platform'),(select id from departments where department_name='All Departments'),'Platform Owner','Satguru AI Platform','support@app.satguruai.com','live','logged_in') on conflict do nothing;
insert into announcements (title, message, priority) values ('MVP launch foundation','The central portal now provides a governed directory, support flow, and admin-ready management screens.','high');
